language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - MAKEFILE=Makefile.linux
        - LIB_NAME=libopenctm.so
    - os: osx
      language: generic
      env:
        - PIP=pip2
        - MAKEFILE=Makefile.macosx
        - LIB_NAME=libopenctm.dylib

env:
  global:
    - TWINE_USERNAME=lejafar

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      bash travis/build-openctm.sh $MAKEFILE $LIB_NAME
      $PIP install pyOpenSSL ndg-httpsclient pyasn1
    else
      docker run -v $PWD/openctm:/openctm -v $PWD/travis:/travis quay.io/pypa/manylinux1_x86_64 bash /travis/build-openctm.sh $MAKEFILE $LIB_NAME
    fi

after_install:
  - python3 -m unittest discover -s tests/  -vvv

script:
  - $PIP install cibuildwheel==0.9.4
  - touch stub.cc
  - cibuildwheel --output-dir wheelhouse
  - python -m pip install twine
  - python -m twine upload wheelhouse/*.whl
