language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
    - CIBW_SKIP=cp33-*
    - TWINE_USERNAME=lejafar

script:
  - touch stub.cc
  - $PIP install cibuildwheel==0.7.1
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
    fi
