language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"

env:
  global:
    - TWINE_USERNAME=lejafar

script:
  - python setup.py sdist bdist_wheel
  - python -m pip install twine
  - python -m twine upload dist/*
