language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - MAKEFILE=Makefile.linux
        - LIB_NAME=libopenctm.so
    - os: osx
      language: generic
      env:
        - PIP=pip2
        - MAKEFILE=Makefile.macosx
        - LIB_NAME=libopenctm.dylib

env:
  global:
    - CIBW_SKIP=cp33-*
    - TWINE_USERNAME=lejafar

script:
  - docker run -v openctm:openctm quay.io/pypa/manylinux1_x86_64 bash travis/build-openctm.sh $MAKEFILE $LIB_NAME
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      $PIP install pyOpenSSL ndg-httpsclient pyasn1
    fi
  - $PIP install cibuildwheel==0.7.1
  - touch stub.cc
  - cibuildwheel --output-dir wheelhouse
  - python -m pip install twine
  - python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
