language: python

python:
    - "3.7"

env:
  global:
    - TWINE_USERNAME=lejafar

install:
  - python -m pip install pipenv
  - pipenv install -d

script:
  - pipenv run pytest tests/
  - python setup.py sdist bdist_wheel
  - python -m pip install twine
  - python -m twine upload dist/*
