environment:
  matrix:
    # VS 2015
    - BUILD_TYPE: nmake
      VS_VERSION: Visual Studio 14
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

environment:
  global:
    TWINE_USERNAME: lejafar

build_script:
  - bash travis/build-openctm-win.sh
  - pip install cibuildwheel==0.9.4
  - touch stub.cc
  - cibuildwheel --output-dir wheelhouse
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        python -m pip install twine
        python -m twine upload (resolve-path wheelhouse\*.whl)
      }
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels