environment:
  global:
    CIBW_TEST_REQUIRES: nose
    CIBW_TEST_COMMAND: "nosetests {project}\\tests"
    TWINE_USERNAME=lejafar
    # Note: TWINE_PASSWORD is set in Appveyor settings

build_script:
  - bash travis/build-openctm-win.sh
  - pip install cibuildwheel==0.9.4
  - touch stub.cc
  - cibuildwheel --output-dir wheelhouse
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        python -m pip install twine
        python -m twine upload (resolve-path wheelhouse\*.whl)
      }
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels