# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [3.7]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Run tests
        run: |
          python -m pip install pipenv==2018.11.26
          pipenv install -d
          pipenv run pip list
          pipenv run pip show python-openctm
          pipenv run pytest tests
        shell: bash
